module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "perf",
        "security",
        "refactor",
        "test",
        "docs",
        "chore",
        "ci",
        "revert",
        "style",
        "workflow",
      ],
    ],
    "type-case": [2, "always", "lower-case"],
    "type-empty": [2, "never"],
    "scope-case": [2, "always", "kebab-case"],
    "scope-enum": [
      1,
      "always",
      [
        "core",
        "common",
        "cli",
        "testing",
        "payment",
        "whatsapp",
        "webhook",
        "graphql",
        "database",
        "plugin-orange-money",
        "plugin-wave",
        "plugin-mtn-momo",
        "plugin-whatsapp",
        "plugin-sms",
        "docs",
        "deps",
        "config",
        "ci",
        "tooling",
        "release",
        "workspace",
        "changeset",
        "community",
        "dx",
        "legal",
        "assets",
        "github",
        "workflow",
      ],
    ],
    "subject-empty": [2, "never"],
    "subject-case": [0], // Disabled: Allow any case for flexibility
    "subject-max-length": [1, "always", 100], // Warning instead of error
    "subject-full-stop": [1, "never", "."],
    "header-max-length": [1, "always", 100],
    "body-leading-blank": [1, "always"],
    "body-max-line-length": [0], // Disabled
    "footer-leading-blank": [1, "always"],
    "footer-max-line-length": [1, "always", 100],
  },
  helpUrl: "https://docs.shoperzz.dev/contributing/commits",
};
